<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://res.wx.qq.com/open/libs/weui/1.1.0/weui.min.css">
    <script type="text/javascript" src="https://res.wx.qq.com/open/libs/weuijs/1.1.1/weui.min.js"></script>
    <title>Phalcon PHP Framework</title>
</head>
<body>
<div class="container">
    <div class="page">
        <div class="weui-msg">
            <input id="authKey" value="<?=$authKey;?>" type="hidden"/>
            <div class="weui-msg__icon-area"><i class="weui-icon-warn weui-icon_msg"></i></div>
            <div class="weui-msg__text-area">
                <h2 class="weui-msg__title">确认登录</h2>
                <p class="weui-msg__desc">即将登录<a href="javascript:void(0);">快捷行</a>，请确认是本人登录。如果非本人登录请取消操作</p>
            </div>
            <div class="weui-msg__opr-area">
                <p class="weui-btn-area">
                    <a id="confirm" class="weui-btn weui-btn_primary">确认登录</a>
                    <a id="cancel" class="weui-btn weui-btn_default">取消</a>
                </p>
            </div>
            <div class="weui-msg__extra-area">
                <div class="weui-footer">
                    <p class="weui-footer__links">
                        <a href="javascript:void(0);" class="weui-footer__link">底部链接文本</a>
                    </p>
                    <p class="weui-footer__text">Copyright &copy; 2008-2016 weui.io</p>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(function () {
        $("#confirm").on("click",function () {
            setAuth(1);
        });

        $("#cancel").on("click",function () {
            setAuth(0);
        });

        function setAuth(status) {
            $.post('/setAuth',{authKey:$("#authKey").val(),status:status},function (res) {
                if(res.code ==1){
                    weui.toast(res.msg, {
                        duration: 2000,
                        className: 'custom-classname',
                        callback: function(){
                            WeixinJSBridge.call('closeWindow');
                        }
                    });
                }else{
                    weui.topTips(res.msg, 3000);
                }
            },'json')
        }
    })
</script>
</body>
</html>
