<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://res.wx.qq.com/open/libs/weui/1.1.0/weui.min.css">
    <script type="text/javascript" src="https://res.wx.qq.com/open/libs/weuijs/1.1.1/weui.min.js"></script>
    <title>Phalcon PHP Framework</title>
</head>
<body>
<div class="container">
    <div class="page">
        <div class="weui-msg">
            <br>
            <div class="weui-msg__icon-area"><i class="weui-icon-warn weui-icon_msg"></i></div>
            <br/>
            <div class="weui-msg__text-area">
                <h2 class="weui-msg__title"><?=$error;?></h2>
            </div>
            <div class="weui-msg__extra-area">
                <div class="weui-footer">
                    <p class="weui-footer__text">Copyright &copy; fastgoo.net</p>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
