<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://res.wx.qq.com/open/libs/weui/1.1.0/weui.min.css">
    <script type="text/javascript" src="https://res.wx.qq.com/open/libs/weuijs/1.1.1/weui.min.js"></script>
    <title>授权登录</title>
</head>
<body>

<div class="page">
    <div class="page__hd">
        <br/>
        <p class="page__desc" style="text-align: center">二维码扫描跳转</p>
        <div style="text-align: center">
            <embed width="320" height="320" id="qrcode" src="" type="image/svg+xml"/>
        </div>

    </div>
    <div class="page__bd">
        <div class="weui-cells weui-cells_form">
            <div class="weui-cell">
                <div class="weui-cell__bd">
                    <textarea id="redirectUrl" class="weui-textarea" placeholder="请输入跳转的URL地址" rows="3"></textarea>
                    <div class="weui-textarea-counter"><span>0</span>/200</div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<script>
    $(function () {
        var authKey;
        getQrcode();
        function getQrcode() {
            authKey = parseInt(Math.random() * (999999 - 100000 + 1) + 100000);
            $("#qrcode").attr('src', "https://wechat.zhoujianjun.cn/getQrcode?authKey=" + authKey);
        }

        function getAuthStatus() {
            console.log($("#redirectUrl").val());
            $.post('/getAuth', {authKey: authKey}, function (res) {
                if (res.code == 1) {
                    location.herf = $("#redirectUrl").val() + "&wechatToken=" + res.data.token;
                }
                if (res.code == -1 || res.code == -5) {
                    alert(res.msg);
                }
            }, 'json')
        }

        setTimeout(function () {
            window.setInterval(getAuthStatus, 2000);
        },10000);
    })
</script>
</body>
</html>
